name = "sarkari-yojana"
compatibility_date = "2026-06-19"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "sarkari-yojana-db"
database_id = "4f490775-4109-47d7-9487-f46c422e4156"

[triggers]
crons = ["0 */6 * * *"]
