name = "sarkari-yojana"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "sarkari-yojana-db"
database_id = "4f490775-4109-47d7-9487-f46c422e4156"
